language: python
sudo: required
dist: trusty
python:
  - 3.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - python setup.py install
  - echo "[global] " > ~/.theanorc
  - echo "floatX = float32" >> ~/.theanorc
script:
  - py.test --ignore=build --cov
after_success:
  - coveralls
notifications:
  email: philippe.chavanne@gmail.com
